// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjeDUYA8nHX-0eeYR4vBmRawqVALfB-N4',
    appId: '1:134323372396:web:f1f1f782af119c3b64f349',
    messagingSenderId: '134323372396',
    projectId: 'wave-learning-app',
    authDomain: 'wave-learning-app.firebaseapp.com',
    storageBucket: 'wave-learning-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARAsDi5TC6eARdOD_rT44clCkVG6fIQ8',
    appId: '1:134323372396:android:ec4a08a87948617964f349',
    messagingSenderId: '134323372396',
    projectId: 'wave-learning-app',
    storageBucket: 'wave-learning-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzPtmwQ66JJWV07ygLdyrJZHzeYxdQmxQ',
    appId: '1:134323372396:ios:b88de1b2f1808ffb64f349',
    messagingSenderId: '134323372396',
    projectId: 'wave-learning-app',
    storageBucket: 'wave-learning-app.appspot.com',
    iosBundleId: 'com.example.waveLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzPtmwQ66JJWV07ygLdyrJZHzeYxdQmxQ',
    appId: '1:134323372396:ios:b88de1b2f1808ffb64f349',
    messagingSenderId: '134323372396',
    projectId: 'wave-learning-app',
    storageBucket: 'wave-learning-app.appspot.com',
    iosBundleId: 'com.example.waveLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjeDUYA8nHX-0eeYR4vBmRawqVALfB-N4',
    appId: '1:134323372396:web:0072faa8a628bbd064f349',
    messagingSenderId: '134323372396',
    projectId: 'wave-learning-app',
    authDomain: 'wave-learning-app.firebaseapp.com',
    storageBucket: 'wave-learning-app.appspot.com',
  );
}
